SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

TILE_SIZE = 64

LEFT_BORDER = SCREEN_WIDTH//2 - TILE_SIZE * 4
TOP_BORDER = SCREEN_HEIGHT//2 - TILE_SIZE * 4

BLACK = 0
WHITE = 1

TIME_LIMIT = 180.

HUMAN = BLACK
